version: "2"
services:
    product-service:
        build: ./product-service 
        ports:
            - 9090:9090
        volumes:
            - ./product-service:/go/src/grpc-go-kit-example/product-service:cached
    graphql-gateway:
        build: ./graphql-gateway 
        ports:
            - 4000:4000
        volumes:
            - ./graphql-gateway:/go/src/grpc-go-kit-example/graph-gateway:cached
        links:
            - product-service
